#!/usr/bin/env bash
set -e
cd /c/Users/gpoli/GIT/AI_Agents_V11_cleanup/AI_agents
echo "Batch 1/4 (30 files)"
git mv "ADAPTIVE_INVESTIGATION_FLOWCHART.txt" "archive/timelines_and_reports/ADAPTIVE_INVESTIGATION_FLOWCHART.txt"
git mv "add_email_badge_script.ps1" "archive/timelines_and_reports/add_email_badge_script.ps1"
git mv "apply_automation_slug_migration.ps1" "archive/timelines_and_reports/apply_automation_slug_migration.ps1"
git mv "apply_comm_hub_fixes.ps1" "archive/timelines_and_reports/apply_comm_hub_fixes.ps1"
git mv "APPLY_PRIME_LOADED_FIX.ps1" "archive/timelines_and_reports/APPLY_PRIME_LOADED_FIX.ps1"
git mv "architecture_diagram_content_blocks.svg" "archive/timelines_and_reports/architecture_diagram_content_blocks.svg"
git mv "batch_add_short_descriptions.ps1" "archive/timelines_and_reports/batch_add_short_descriptions.ps1"
git mv "BISTART_current.txt" "archive/timelines_and_reports/BISTART_current.txt"
git mv "BISTARTVALOR.ps1" "archive/timelines_and_reports/BISTARTVALOR.ps1"
git mv "CHAT_SIDEBAR_REGISTRATION_TEST.js" "archive/timelines_and_reports/CHAT_SIDEBAR_REGISTRATION_TEST.js"
git mv "CHAT_SIDEBAR_SMOKE_TEST.js" "archive/timelines_and_reports/CHAT_SIDEBAR_SMOKE_TEST.js"
git mv "check_message_order.js" "archive/timelines_and_reports/check_message_order.js"
git mv "check_v10_deployment.ps1" "archive/timelines_and_reports/check_v10_deployment.ps1"
git mv "comment_all_font_weights_final.ps1" "archive/timelines_and_reports/comment_all_font_weights_final.ps1"
git mv "comment_font_weights.ps1" "archive/timelines_and_reports/comment_font_weights.ps1"
git mv "comment_font_weights_v2.ps1" "archive/timelines_and_reports/comment_font_weights_v2.ps1"
git mv "comment_remaining_font_weights.ps1" "archive/timelines_and_reports/comment_remaining_font_weights.ps1"
git mv "COMMIT_COMMANDS.txt" "archive/timelines_and_reports/COMMIT_COMMANDS.txt"
git mv "complete_test_run.txt" "archive/timelines_and_reports/complete_test_run.txt"
git mv "create_threads_table_render.sh" "archive/timelines_and_reports/create_threads_table_render.sh"
git mv "database_data_locations.txt" "archive/timelines_and_reports/database_data_locations.txt"
git mv "debug_css_leak.js" "archive/timelines_and_reports/debug_css_leak.js"
git mv "debug_kanban_board.js" "archive/timelines_and_reports/debug_kanban_board.js"
git mv "debug_message_count.js" "archive/timelines_and_reports/debug_message_count.js"
git mv "diagnose_kanban_dashboard.html" "archive/timelines_and_reports/diagnose_kanban_dashboard.html"
git mv "DIAGNOSE_TRANSCRIPTION_SIDEBAR.ps1" "archive/timelines_and_reports/DIAGNOSE_TRANSCRIPTION_SIDEBAR.ps1"
git mv "diagnostic_agent_loading.js" "archive/timelines_and_reports/diagnostic_agent_loading.js"
git mv "FIX_HTML_STRUCTURE.ps1" "archive/timelines_and_reports/FIX_HTML_STRUCTURE.ps1"
git mv "FIX_MISSING_BUTTONS.js" "archive/timelines_and_reports/FIX_MISSING_BUTTONS.js"
git mv "fix_schema_required.ps1" "archive/timelines_and_reports/fix_schema_required.ps1"
git commit -m "chore(cleanup/root-scripts-row52): batch 1/4 (30 one-shot root files to archive)" >/dev/null 2>&1
echo "  committed batch 1"
echo "Batch 2/4 (30 files)"
git mv "fix_ui_paths.ps1" "archive/timelines_and_reports/fix_ui_paths.ps1"
git mv "fix_ui_paths_round2.ps1" "archive/timelines_and_reports/fix_ui_paths_round2.ps1"
git mv "flask_debug_output.txt" "archive/timelines_and_reports/flask_debug_output.txt"
git mv "force_reload_agent2_with_logging.js" "archive/timelines_and_reports/force_reload_agent2_with_logging.js"
git mv "full_test_output.txt" "archive/timelines_and_reports/full_test_output.txt"
git mv "integrate-synergy-realtime.sh" "archive/timelines_and_reports/integrate-synergy-realtime.sh"
git mv "MASTER_PRIME_DEBUGGER.js" "archive/timelines_and_reports/MASTER_PRIME_DEBUGGER.js"
git mv "MESSAGE_TIMESTAMP_UI_IMPLEMENTATION.js" "archive/timelines_and_reports/MESSAGE_TIMESTAMP_UI_IMPLEMENTATION.js"
git mv "meta_test_output.txt" "archive/timelines_and_reports/meta_test_output.txt"
git mv "output.txt" "archive/timelines_and_reports/output.txt"
git mv "PRIME_ROOT_CAUSE_FINDER.js" "archive/timelines_and_reports/PRIME_ROOT_CAUSE_FINDER.js"
git mv "QUICK_REFERENCE_CARD.txt" "archive/timelines_and_reports/QUICK_REFERENCE_CARD.txt"
git mv "render-docker.yaml" "archive/timelines_and_reports/render-docker.yaml"
git mv "render-v10.yaml" "archive/timelines_and_reports/render-v10.yaml"
git mv "render_cleaned.yaml" "archive/timelines_and_reports/render_cleaned.yaml"
git mv "RENDER_CREDENTIALS_TEMPLATE.txt" "archive/timelines_and_reports/RENDER_CREDENTIALS_TEMPLATE.txt"
git mv "RENDER_DOWNLOAD_UPDATED_DBS.sh" "archive/timelines_and_reports/RENDER_DOWNLOAD_UPDATED_DBS.sh"
git mv "RENDER_V10_ENV_VARS.txt" "archive/timelines_and_reports/RENDER_V10_ENV_VARS.txt"
git mv "requirements_text_extraction.txt" "archive/timelines_and_reports/requirements_text_extraction.txt"
git mv "SEARCH_TERM_DEMONSTRATION.txt" "archive/timelines_and_reports/SEARCH_TERM_DEMONSTRATION.txt"
git mv "semantic_test_20_more_results.txt" "archive/timelines_and_reports/semantic_test_20_more_results.txt"
git mv "semantic_test_results.txt" "archive/timelines_and_reports/semantic_test_results.txt"
git mv "SETTINGS_BUTTON_INTEGRATION.html" "archive/timelines_and_reports/SETTINGS_BUTTON_INTEGRATION.html"
git mv "SHIPPING_INTEGRATION_DIAGRAM.txt" "archive/timelines_and_reports/SHIPPING_INTEGRATION_DIAGRAM.txt"
git mv "SPIRAL_FIXED_FEE_IMPACT_ANALYSIS.txt" "archive/timelines_and_reports/SPIRAL_FIXED_FEE_IMPACT_ANALYSIS.txt"
git mv "START_WITH_SUPABASE.ps1" "archive/timelines_and_reports/START_WITH_SUPABASE.ps1"
git mv "SUPABASE_SETUP_COMPLETE.ps1" "archive/timelines_and_reports/SUPABASE_SETUP_COMPLETE.ps1"
git mv "sync-to-valorai.ps1" "archive/timelines_and_reports/sync-to-valorai.ps1"
git mv "synergy_full_output.txt" "archive/timelines_and_reports/synergy_full_output.txt"
git mv "synergy_output.txt" "archive/timelines_and_reports/synergy_output.txt"
git commit -m "chore(cleanup/root-scripts-row52): batch 2/4 (30 one-shot root files to archive)" >/dev/null 2>&1
echo "  committed batch 2"
echo "Batch 3/4 (30 files)"
git mv "synergy_ui_test.html" "archive/timelines_and_reports/synergy_ui_test.html"
git mv "temp_check.txt" "archive/timelines_and_reports/temp_check.txt"
git mv "TEMP_OLD_inhouse-kanban.css" "archive/timelines_and_reports/TEMP_OLD_inhouse-kanban.css"
git mv "TEMP_OLD_inhouse-kanban.js" "archive/timelines_and_reports/TEMP_OLD_inhouse-kanban.js"
git mv "temp_synergy_styles.css" "archive/timelines_and_reports/temp_synergy_styles.css"
git mv "TEMP_V9_analysis.js" "archive/timelines_and_reports/TEMP_V9_analysis.js"
git mv "test-ai-api-sequential.html" "archive/timelines_and_reports/test-ai-api-sequential.html"
git mv "test-ai-tools-flow.html" "archive/timelines_and_reports/test-ai-tools-flow.html"
git mv "test_77_queries_output.txt" "archive/timelines_and_reports/test_77_queries_output.txt"
git mv "test_api_response.js" "archive/timelines_and_reports/test_api_response.js"
git mv "test_comm_hub_simple.html" "archive/timelines_and_reports/test_comm_hub_simple.html"
git mv "test_communication_hub.html" "archive/timelines_and_reports/test_communication_hub.html"
git mv "test_communication_hub_live.html" "archive/timelines_and_reports/test_communication_hub_live.html"
git mv "test_communication_hub_smoke.js" "archive/timelines_and_reports/test_communication_hub_smoke.js"
git mv "test_communication_hub_standalone.html" "archive/timelines_and_reports/test_communication_hub_standalone.html"
git mv "test_communication_with_auth.html" "archive/timelines_and_reports/test_communication_with_auth.html"
git mv "test_email_thread_system.ps1" "archive/timelines_and_reports/test_email_thread_system.ps1"
git mv "test_fix_output.txt" "archive/timelines_and_reports/test_fix_output.txt"
git mv "test_frontend_imports.html" "archive/timelines_and_reports/test_frontend_imports.html"
git mv "test_guide_output.txt" "archive/timelines_and_reports/test_guide_output.txt"
git mv "test_modern_framework_loading.html" "archive/timelines_and_reports/test_modern_framework_loading.html"
git mv "test_output.txt" "archive/timelines_and_reports/test_output.txt"
git mv "test_output_temp.txt" "archive/timelines_and_reports/test_output_temp.txt"
git mv "TEST_PRIME_FIX.js" "archive/timelines_and_reports/TEST_PRIME_FIX.js"
git mv "TEST_PRIME_SCROLL_VISIBILITY.js" "archive/timelines_and_reports/TEST_PRIME_SCROLL_VISIBILITY.js"
git mv "test_result.txt" "archive/timelines_and_reports/test_result.txt"
git mv "test_results.txt" "archive/timelines_and_reports/test_results.txt"
git mv "TEST_SVG_METADATA_HIDING.html" "archive/timelines_and_reports/TEST_SVG_METADATA_HIDING.html"
git mv "test_thinking_separator.js" "archive/timelines_and_reports/test_thinking_separator.js"
git mv "TEST_THREAD_EXPANSION_FIXES.html" "archive/timelines_and_reports/TEST_THREAD_EXPANSION_FIXES.html"
git commit -m "chore(cleanup/root-scripts-row52): batch 3/4 (30 one-shot root files to archive)" >/dev/null 2>&1
echo "  committed batch 3"
echo "Batch 4/4 (12 files)"
git mv "test_thread_id_system.js" "archive/timelines_and_reports/test_thread_id_system.js"
git mv "test_vector_database_v4.html" "archive/timelines_and_reports/test_vector_database_v4.html"
git mv "thread_2111_db_order.txt" "archive/timelines_and_reports/thread_2111_db_order.txt"
git mv "thread_2111_detailed.txt" "archive/timelines_and_reports/thread_2111_detailed.txt"
git mv "THREAD_COPY_OUTPUT_EXAMPLE.txt" "archive/timelines_and_reports/THREAD_COPY_OUTPUT_EXAMPLE.txt"
git mv "thread_locations_export.csv" "archive/timelines_and_reports/thread_locations_export.csv"
git mv "tmp_row52_classification.csv" "archive/timelines_and_reports/tmp_row52_classification.csv"
git mv "tmp_row52_inventory.csv" "archive/timelines_and_reports/tmp_row52_inventory.csv"
git mv "tmp_row52_summary.txt" "archive/timelines_and_reports/tmp_row52_summary.txt"
git mv "track_script_balance.ps1" "archive/timelines_and_reports/track_script_balance.ps1"
git mv "verify_ui_paths.ps1" "archive/timelines_and_reports/verify_ui_paths.ps1"
git mv "watch_dom_mutations.js" "archive/timelines_and_reports/watch_dom_mutations.js"
git commit -m "chore(cleanup/root-scripts-row52): batch 4/4 (12 one-shot root files to archive)" >/dev/null 2>&1
echo "  committed batch 4"
echo "DONE: 4 batches, 102 files moved"
