# ==================== VALOR AI PLATFORM LAUNCHER (PowerShell) ====================
# Launch Flask backend (AI_Agents_V11) connected to ValorAI Supabase database
# Usage: .\BISTARTVALOR.ps1 or just "BISTARTVALOR" if added to PATH

Write-Host ""
Write-Host "============================================================" -ForegroundColor Magenta
Write-Host "   VALOR AI PLATFORM LAUNCHER" -ForegroundColor Yellow
Write-Host "   [ValorAI Supabase - Multi-Tenant Database]" -ForegroundColor Magenta
Write-Host "============================================================" -ForegroundColor Magenta
Write-Host ""

# Set paths
$FLASK_DIR = "C:\Users\gpoli\GIT\AI_Agents_V11\AI_agents\AI_infrastructure"
$UI_DIR = "C:\Users\gpoli\GIT\AI_Agents_V11\AI_agents\UI"
$ORIGINAL_DIR = Get-Location

# Check if Flask app exists
if (-not (Test-Path "$FLASK_DIR\flask_app.py")) {
    Write-Host "[ERROR] Flask app not found at: $FLASK_DIR\flask_app.py" -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
}

# Check if UI exists
if (-not (Test-Path "$UI_DIR\business-ai-platform-v2.html")) {
    Write-Host "[ERROR] UI not found at: $UI_DIR\business-ai-platform-v2.html" -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
}

# Update HTML version timestamp (forces browser cache refresh for ALL files)
Write-Host "[0/5] Updating HTML version + ALL file cache tags..." -ForegroundColor Yellow
$htmlFile = "$UI_DIR\business-ai-platform-v2.html"
$timestamp = Get-Date -Format "yyyyMMdd_HHmm"

try {
    $content = Get-Content $htmlFile -Raw

    # Count total ?v= tags BEFORE replacement
    $versionPattern = '\?v=\d{8}[_\d]*[a-zA-Z]*'
    $beforeCount = ([regex]::Matches($content, $versionPattern)).Count

    # Replace ALL ?v= tags in one pass
    $content = $content -replace $versionPattern, "?v=$timestamp"

    if ($beforeCount -gt 0) {
        Write-Host "      [OK] Updated $beforeCount file cache tags to: $timestamp" -ForegroundColor Green
        Write-Host "      [INFO] Browser cache will be bypassed on next load" -ForegroundColor Cyan
    }
    else {
        Write-Host "      [SKIP] No cache tags found (first run or clean file)" -ForegroundColor Yellow
    }

    # Update existing HTML_VERSION constant or inject it
    if ($content -match "const HTML_VERSION = ") {
        $content = $content -replace "const HTML_VERSION = '[^']*'", "const HTML_VERSION = '$timestamp'"
        Write-Host "      [OK] HTML_VERSION constant updated: $timestamp" -ForegroundColor Green
    }
    else {
        $scriptInjection = @"
<script>
    // Auto-generated by BISTARTVALOR.ps1 - DO NOT EDIT MANUALLY
    const HTML_VERSION = '$timestamp';
    console.log('[CACHE] HTML_VERSION injected:', HTML_VERSION);
    const cached = sessionStorage.getItem('html_version');
    if (cached && cached !== HTML_VERSION) {
        sessionStorage.setItem('html_version', HTML_VERSION);
        location.reload(true);
    } else if (!cached) {
        sessionStorage.setItem('html_version', HTML_VERSION);
    }
</script>
"@
        if ($content -match '(<head[^>]*>)') {
            $content = $content -replace '(<head[^>]*>)', "`$1`n$scriptInjection"
            Write-Host "      [OK] HTML_VERSION constant injected: $timestamp" -ForegroundColor Green
        }
    }

    Set-Content $htmlFile -Value $content -NoNewline
}
catch {
    Write-Host "      [ERROR] Could not update versions: $($_.Exception.Message)" -ForegroundColor Red
}
Write-Host ""

Write-Host "[1/5] Cleaning up zombie Python processes..." -ForegroundColor Yellow

# Kill ALL Python processes (Flask zombies + any leftover processes)
$pythonProcs = Get-Process python -ErrorAction SilentlyContinue
if ($pythonProcs) {
    Write-Host "      Found $($pythonProcs.Count) Python process(es) - stopping all..." -ForegroundColor Yellow
    foreach ($proc in $pythonProcs) {
        Write-Host "      Stopping PID $($proc.Id)..." -ForegroundColor Gray
        Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue
    }
    Start-Sleep -Seconds 2
    Write-Host "      [OK] All Python processes stopped" -ForegroundColor Green
}
else {
    Write-Host "      [OK] No Python processes to clean" -ForegroundColor Green
}
Write-Host ""

Write-Host "[2/5] Checking for existing Flask servers on port 5001..." -ForegroundColor Yellow

# Method 1: Try Get-NetTCPConnection (works on Windows 10+)
try {
    $flaskProcesses = Get-NetTCPConnection -LocalPort 5001 -State Listen -ErrorAction Stop |
    Select-Object -ExpandProperty OwningProcess -Unique |
    ForEach-Object { Get-Process -Id $_ -ErrorAction SilentlyContinue } |
    Where-Object { $_ -ne $null }

    if ($flaskProcesses) {
        Write-Host "      Found $($flaskProcesses.Count) process(es) on port 5001" -ForegroundColor Yellow
        foreach ($proc in $flaskProcesses) {
            Write-Host "      Stopping PID $($proc.Id) ($($proc.ProcessName))..." -ForegroundColor Gray
            Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue
        }
        Start-Sleep -Seconds 2
        Write-Host "      [OK] Port 5001 cleared" -ForegroundColor Green
    }
    else {
        Write-Host "      [OK] Port 5001 is available" -ForegroundColor Green
    }
}
catch {
    # Method 2: Fallback using netstat (works on all Windows versions)
    Write-Host "      Using fallback method (netstat)..." -ForegroundColor Gray
    $netstatOutput = netstat -aon | Select-String ":5001.*LISTENING"

    if ($netstatOutput) {
        $pids = $netstatOutput | ForEach-Object {
            if ($_ -match '\s+(\d+)\s*$') { $matches[1] }
        } | Select-Object -Unique

        Write-Host "      Found $($pids.Count) process(es) on port 5001" -ForegroundColor Yellow
        foreach ($processId in $pids) {
            Write-Host "      Stopping PID $processId..." -ForegroundColor Gray
            Stop-Process -Id $processId -Force -ErrorAction SilentlyContinue
        }
        Start-Sleep -Seconds 2
        Write-Host "      [OK] Port 5001 cleared" -ForegroundColor Green
    }
    else {
        Write-Host "      [OK] Port 5001 is available" -ForegroundColor Green
    }
}
Write-Host ""

Write-Host "[3/5] Starting Flask Backend with ValorAI Supabase..." -ForegroundColor Green
Write-Host "      Location: $FLASK_DIR" -ForegroundColor Gray
Write-Host "      Port: 5001" -ForegroundColor Gray
Write-Host "      Database: ValorAI Supabase (aeazscmhmoipfchuwcih)" -ForegroundColor Magenta
Write-Host ""

# Start Flask in new PowerShell window with ValorAI Supabase environment variables
$flaskCommand = @"
Set-Location '$FLASK_DIR'
`$env:PYTHONIOENCODING='utf-8'
`$env:DEBUG='true'
`$env:FLASK_ENV='development'
`$env:USE_SUPABASE='true'
`$env:RENDER='true'
`$env:SUPABASE_URL=$env:VALORAI_SUPABASE_URL
`$env:SUPABASE_SERVICE_KEY=$env:VALORAI_SUPABASE_SERVICE_KEY
`$env:SUPABASE_ANON_KEY=$env:VALORAI_SUPABASE_ANON_KEY
`$env:SUPABASE_DB_URL=$env:VALORAI_SUPABASE_DB_URL
Write-Host ''
Write-Host '[VALOR AI MODE] Connected to ValorAI Multi-Tenant Database' -ForegroundColor Magenta
Write-Host '[DEV MODE] Debug enabled - dev-mode-token accepted' -ForegroundColor Yellow
Write-Host 'Flask Backend Running on http://localhost:5001' -ForegroundColor Green
Write-Host ''
python flask_app.py
"@

Start-Process powershell -ArgumentList "-NoExit", "-Command", $flaskCommand

# Wait 3 seconds for Flask to initialize
Start-Sleep -Seconds 3

Write-Host "[4/5] Opening Platform in Browser..." -ForegroundColor Green
Write-Host ""

Write-Host "      Opening http://localhost:5001 in new browser window..." -ForegroundColor Gray
Start-Process "http://localhost:5001" -ArgumentList "--new-window"

Write-Host ""
Write-Host "============================================================" -ForegroundColor Magenta
Write-Host "   VALOR AI PLATFORM LAUNCHED SUCCESSFULLY!" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Magenta
Write-Host ""
Write-Host "    Platform URL:   http://localhost:5001" -ForegroundColor Yellow
Write-Host "    Database:       ValorAI Supabase (aeazscmhmoipfchuwcih)" -ForegroundColor Magenta
Write-Host "    UI opened in default browser" -ForegroundColor White
Write-Host ""
Write-Host "    1 PowerShell window opened:" -ForegroundColor White
Write-Host "    - Flask Backend (Port 5001)" -ForegroundColor Gray
Write-Host ""
Write-Host "    Press Ctrl+C in each window to stop servers" -ForegroundColor Magenta
Write-Host ""
Write-Host "============================================================" -ForegroundColor Magenta

# Return to original directory
Set-Location $ORIGINAL_DIR

Write-Host ""
Read-Host "Press Enter to exit launcher"
